### ISSUE TITLE
Coherence Support for .NET Core?

### ISSUE THREAD

**Issue by mpekurny** [oracle/coherence-dotnet-extend-client#1]
It appears that this is .NET Framework 4.0. Is there a planned support for .NET Core?

**Comment by harveyraja** [comment]
Nothing planned @mpekurny, but certainly happy to consider it.

**Comment by mpekurny** [comment]
Is there an official way to put in the request for .NET Core support? We already have applications running on Linux in .NET Core that we would be looking to add caching support for. Since they are running on Linux .NET Framework isn't an option for us.

**Comment by harveyraja** [comment]
A couple of questions @mpekurny:

1. Are you already using Coherence and this is an extension of that use or is this an entirely new use?
1. Whats your timeline for adding caching support?

Happy to log an official enhancement on your behalf. Would be great to have a bit more context such as the use case, the company/application, etc, to prioritize development during planning exercises. Feel free to reach out over DM on [slack](oraclecoherence.slack.com) if you prefer.

**Comment by mpekurny** [comment]
I work for Paychex, Inc on some of their web based offerings. I am working on creating better parity between our Java and .NET development [stack/tools]. Currently our Java development uses Coherence to cache data for reuse. For .NET development we often use in-memory caches or no caching at all. To make our solutions more consistent across both technologies, we would like to offer an enterprise caching solution like Coherence for our .NET development as well. For your questions above:

1. Are you already using Coherence and this is an extension of that use or is this an entirely new use? - While we are using Coherence for Java development, this would be entirely new for our .NET applications.
2. Whats your timeline for adding caching support? - As this is an effort to bring parity between our Java and .NET and with Java already having a solution, the sooner the better. However, a realistic expectation would be that we would like to see some sort of solution in place within the next 6-8 months.

**Comment by harveyraja** [comment]
Thanks @mpekurny. I have logged the feature request (FYI internal JIRA reference is COH-21431), and will evaluate during our next milestone planning.

Note: we will keep this issue updated as we make progress.

**Comment by mpekurny** [comment]
Awesome, thanks so much

**Comment by amitdhanuka** [comment]
@harveyraja Could you provide any ETA. We are already using coherence in .Net Framework 4 applications and we are migrating those application to .Net Core.
Your ETA can help us in taking further decision.

**Comment by aseovic** [comment]
@mpekurny Have you tried changing the dependency from .NET Framework 4.0 to .NET Core and compiling?

Technically, I don't think there is a reason it shouldn't work, as we really only use low level functionality, such as built-in collections, threads and I/O classes within .NET client.

We are happy to look into it as well, but just trying to speed up the process. After all, we **can** accept PRs now ;-)

**Comment by amitdhanuka** [comment]
Installing this package from Nuget in a .Net Core 3.1 applicatioon gives bellow warning. It 's not able to restore using .Net Core.
I can't use this in production environment.

![image](https://user-images.githubusercontent.com/6891066/90308225-6ae87c00-defb-11ea-9d6d-fdafb35918ad.png)


@aseovic  You should consider recompile this package using .Net Core SDK so that it will be supported for .Net Core 3.1 also.

**Comment by mpekurny** [comment]
@aseovic I tried pulling down the source and just rebuilding targeting .NET Core 3.1. It looks like there are several namespaces that have moved or do not exist in .NET Core starting with System.Web.Hosting. I did not spend a great deal of time on it, but it's not just as simple as switch the target and recompile.

**Comment by amitdhanuka** [comment]
@mpekurny, You are correct. It's not that simple to switch the target & just recompile. Many libraries are renamed or deprecated. Also the project structure got changed in .Net Core. This will be writing the same application again in new framework.

**Comment by aseovic** [comment]
@mpekurny It sounds like .NET Core doesn't have support for ASP.NET, so we probably need to separate (or remove) ASP.NET session store implementation.

TBH, I haven't looked at .NET in years, so I'm not quite sure what the scope of the changes will be at this point. If the classes have truly moved around that much, as @amitdhanuka suggests, it may not be worth the effort to support .NET Core with **this** .NET client implementation.

We do have a new, gRPC-based .NET client on the road map, so maybe that's where we focus on .NET Core support, although I am a bit concerned about the differences. What do other libraries do to support both .NET Core and .NET Framework? I really hope the answer is not "maintain two separate code lines", as that would make things significantly more complex :-(

**Comment by aseovic** [comment]
This is gonna be fun...

It seemed for a minute that supporting .NET Standard is the way to go, but Microsoft being Microsoft, with its piss poor record of preserving backwards compatibility, they "de-standardized" the standard pretty much as soon as they created it.

> .NET Framework won't support .NET Standard 2.1 or later versions. For more details, see the announcement of .NET Standard 2.1 (https://devblogs.microsoft.com/dotnet/announcing-net-standard-2-1/).

The bottom line is that Microsoft basically decided to kill .NET Framework and all new development is going into .NET Core **only**, which begs the question which versions/frameworks should our client(s) support.

To make things even messier, there are two .NET implementations of gRPC: the old one, which essentially wraps native gRPC C library using P/Invoke, and works with .NET Framework 4.5 and .NET Standard 2.0, and the new one, which is written in C# and depends on .NET Core 3.0 and .NET Standard 2.1:

> Please note that gRPC for .NET does not replace gRPC for C# (gRPC C# API over native C-core binaries). These implementations coexist and share many of the same APIs to avoid lock-in. There are currently no plans for one implementation to replace the other one. gRPC for C# is the recommended solution for frameworks that gRPC for .NET does not support, such as .NET Framework.

What a nightmare...

@mpekurny @amitdhanuka Which version of .NET Framework and/or .NET Core are you using, and what are your thoughts on the versions we should look to support long term?

Right now I'm leaning towards possibly upgrading this client to support .NET 4.6.1+ and .NET Standard/.NET Core 2.0 (if it's not too much work), which would basically be EoL for it, and supporting **only** .NET Core 3.0+ and .NET Standard 2.1+ in the new client and going forward, so we can use the latest gRPC client.

Does that sound reasonable?

**Comment by mpekurny** [comment]
> Right now I'm leaning towards possibly upgrading this client to support .NET 4.6.1+ and .NET Standard/.NET Core 2.0 (if it's not too much work), which would basically be EoL for it, and supporting only .NET Core 3.0+ and .NET Standard 2.1+ in the new client and going forward, so we can use the latest gRPC client.

I am using .NET Core 3.1 so this plan works for me as long as the new client doesn't take years to create. If you follow the thread above, I was hoping to have something usable by the end of the year. 

My suggestion for this client, if you were to do anything,  would be to split it into a couple libraries. Make a base library that is built to .NET Standard 2.0. And because .NET Core 2.0+ (including 3.1) and .NET Framework 4.6.1+ are able to build with any library that targets that standard version, it would be usable by any .NET flavor out there currently. This new client should handle most of the core functionality of this needed for Coherence and should be usable on it's own, but would not have a the framework specific code that makes integrating with things like ASP.NET, Windows Forms, and WPC easier included.

Then create a library targeting .NET Framework 4.6.1 that depends on the library above with the ASP.NET, Windows Forms, and WPC implementations that aren't supported in .NET Standard. 

Then, bonus points if you create an equivalent .NET Core library that supports ASP.NET Core 2.0 in the same way as the Framework library. But again, if you are going to focus on a new Coherence package that will replace this and support .NET Core 3.0+ then that may not be the best use of your time.

**Comment by aseovic** [comment]
> My suggestion for this client, if you were to do anything, would be to split it into a couple libraries. Make a base library that is built to .NET Standard 2.0. And because .NET Core 2.0+ (including 3.1) and .NET Framework 4.6.1+ are able to build with any library that targets that standard version, it would be usable by any .NET flavor out there currently. This new client should handle most of the core functionality of this needed for Coherence and should be usable on it's own, but would not have a the framework specific code that makes integrating with things like ASP.NET, Windows Forms, and WPC easier included.

Yup, that's pretty much what I had in mind. We'll see how it goes once we start working on it, but it does seem like a reasonable plan.

As for ASP.NET session support, we'll likely leave the existing client as is, and implement ASP.NET Core support in the new client.

**Comment by aseovic** [comment]
@mpekurny @amitdhanuka If you want to give it a try, I just published RC for the .NET Core-based client to NuGet: https://www.nuget.org/packages/Coherence.Core/

The plan is to release it as a different assembly, `Coherence.Core.dll`, but with the exact same API, apart from things that have been removed because they don't exist in .NET Core (legacy ASP.NET, WPF and WinForms support).

Feedback is appreciated, I'd like to get the final release out asap. Thanks!

**Comment by aseovic** [comment]
Coherence Client for .NET Core 3.1 and .NET Standard 2.0 has been released and is available on NuGet:
https://www.nuget.org/packages/Coherence.Core/

Release notes are available here:
https://github.com/oracle/coherence-dotnet-extend-client/releases/tag/14.1.1.3-core

Enjoy!
