### ISSUE TITLE
SSL Remote Certificate Validator - Insecure Defaults

### ISSUE THREAD

**Issue by kmgoudarzi** [oracle/coherence-dotnet-extend-client#8]
# Description
Tangosol.Net. SslStreamProvider - has insecure defaults.  The default SSL Certificate Validator allows RemoteCertificateNameMismatch.  

See [Tangosol.Net. SslStreamProvider:272](https://github.com/oracle/coherence-dotnet-extend-client/blob/4f9d87f80a881a8fed504311757e071d9dfa17d6/src/Coherence/Net/SslStreamProvider.cs#L272)  
 
The correct behaviour can be achieved by replacing 

```
RemoteCertificateValidator = xmlSub == null
                        ? DefaultCertificateValidation
                        : XmlHelper.CreateDelegate<RemoteCertificateValidationCallback>(xmlSub.GetElement("delegate"));
```

with

```
RemoteCertificateValidator = xmlSub == null
                        ? StrictCertificateValidation
                        : XmlHelper.CreateDelegate<RemoteCertificateValidationCallback>(xmlSub.GetElement("delegate"));
```

# Reproduce
Secure your extent-proxy with any valid SSL certificate on a host with a different name to what the certificate was issued for.   Access the extend proxy from an extend client and the SSL handshake will succeed.  

# Expected Behaviour
SSL Handshake should fail with an error.

**Comment by chpatel3** [comment]
Thanks @kmgoudarzi for finding and reporting the issue! Now this is fixed with commit 2ae337d1dd4271e12169296d53ebfb90c2873df5
