### ISSUE TITLE
Broken Extend Proxy SSLHandling  - Correct Server SSL Certificate fail with RemoteCertificateNameMismatch  

### ISSUE THREAD

**Issue by kmgoudarzi** [oracle/coherence-dotnet-extend-client#9]
# Description
The SSL Handshake between Extend-Client and an SSL secured Extend-Proxy fails with **RemoteCertificateNameMismatch** when Certificate is correctly generated to match extend proxy host name.

# Reproduce
1. Generate a valid SSL Certificate with a CN matching the host on which the extend proxy is running.  
2. Secure the Extend Proxy with the SSL certificate 
3. Configure Extend Client to connect to SSL Secured Extend Proxy
4. Configure Extend Client Configuration to use *Tangosol.Net.SslStreamProvider.StrictCertificateValidation* as the **remote-certificate-validator** (or write one which does not allow SSL Handshake errors)
5. Attempt to establish a connection between the client and proxy 
 
The SSL handshake will fail with **RemoteCertificateNameMismatch**.

# Expected Behaviour 
The SSL handshake should succeed. 

# Cause
The cause of this error is due to the parameters passed to the [System.Net.Security.SslStream.AuthenticateAsClient](https://docs.microsoft.com/en-us/dotnet/api/system.net.security.sslstream.authenticateasclient?view=netcore-3.1#System_Net_Security_SslStream_AuthenticateAsClient_System_String_System_Security_Cryptography_X509Certificates_X509CertificateCollection_System_Security_Authentication_SslProtocols_System_Boolean_) method.

In [Tangosol.net.SslStreamProvider:182](https://github.com/oracle/coherence-dotnet-extend-client/blob/4f9d87f80a881a8fed504311757e071d9dfa17d6/src/Coherence/Net/SslStreamProvider.cs#L182), the **serverName** is always the IP Address of the targetHost and not the Fully Qualified Domain Name of the host. 

This goes back to [Tangosol.net.SslStreamProvider:172](https://github.com/oracle/coherence-dotnet-extend-client/blob/4f9d87f80a881a8fed504311757e071d9dfa17d6/src/Coherence/Net/SslStreamProvider.cs#L172) where **SslStreamProvider.ServerName** is not correctly initialised  at the point of creating the SslStreamProvider and is always null.  

Correctly initialising the **serverName** with the FQDN of the remote endpoint would resolve this issue

I'm not sure about the correct place **SslStreamProvider.ServerName** should be initialised but a quick fix would be to replace SslStreamProvider:172

```
                string serverName = string.IsNullOrEmpty(ServerName)
                        ? ((IPEndPoint)client.Client.RemoteEndPoint).Address.ToString()
                        : ServerName;
```

with 

```
string serverName ;
try {
   // try to get FQDN
   IPHostEntry host = Dns.GetHostEntry(((IPEndPoint)client.Client.RemoteEndPoint).Address);
   serverName = host.HostName ;
} catch (Exception x) 
{
   // failed - revert to IP Address 
   serverName = ((IPEndPoint)client.Client.RemoteEndPoint).Address.ToString();
   CacheFactory.Log("Failed to get FQDN for address " + serverName + " due to " + x.GetType().Name + " - " x.Message, CacheFactory.LogLevel.Warn);
}
```

# Environment 
Not Applicable.

**Comment by chpatel3** [comment]
As you mentioned in cause description the real cause is SslStreamProvider.ServerName is not initialized and to initialize ServerName correctly, you need to specify <ssl><server> element which was missing in the schema.

So with the recent fix in commit 5a98ec8ea17fa0b3d8cb1db3fb3d16c9fdea7fb0, now you can set the ssl/server to correctly initialize SslStreamProvider.ServerName.

**Comment by kmgoudarzi** [comment]
Hi @chpatel3,

   Looking over the fix - I'm not quite following why a new config element was needed here.  The &lt;tcp-initiator&gt; element allows for the specification of the &lt;stream-provider&gt; and a list of &lt;remote-addresses&gt;.    What should happen is that the code should go through the &lt;remote-addresses&gt; and connect to whichever one is available or the load-balancing stipulates.  If SSL is specified for the &lt;steam-provider&gt; then the X509 Certificate returned should be validated.

   The validation should check that the host we ended up connecting with appears in the SAN of the certificate it has supplied and that cert chain path / revocation list are trusted.  So all that is needed is for the code to do is to resolve the IP of the host to its Fully Qualified domain name and it will have the equivalent of the ServerName.

  By adding a single serverName element to the SSL config element aren't we limiting / complicating the configuration?  Please let me know if I've got my wires crossed here but in our use case we have multiple addresses and we won't know ahead of time which one (which serverName) we will connect to.  

please let me have your thoughts.

thanks in advance + kind regards,

Kaveh.

**Comment by chpatel3** [comment]
Hi @kmgoudarzi,

So the config change that was done is for correctly initializing SslStreamProvider.ServerName.

Please look `SslStreamProvider.Config.set` where there was already code exists to initialize SslStreamProvider.ServerName from the config but actually that configuration part was missing in the schema.

216:                IXmlElement xmlSub = xml.GetElement("server");
217:                // configure the target server
218:                if (xmlSub != null)
219:                {
220:                    ServerName = xmlSub.GetString();
221:                }

So specifying the `<server>` in ssl config should have resolve your original issue of RemoteCertificateNameMismatch as in your original description for this issue you've mentioned correctly initialising the SslStreamProvider.serverName with the FQDN of the remote endpoint would resolve this issue.

But now the new valid use case that you bring up of having multiple addresses and don't know ahead of time which one (which serverName) we will connect to.

So here when you say multiple addresses then do you mean you've certificate with multiple identities/dns name?

Didn't specifying the `<server>` element with the wildcard e.g "*.example.com" work for you? I believe specifying the target name similar to that should have matched with SAN of the certificate.

I tried to confirm that but microsoft .NET documentation is not clear about that so could you please file the separate SR (would prefer internal one) if specifying target serverName using wildcard does not work for you.

Thanks!
